In [6]:
import pandas as pd

In [7]:
cr=pd.read_csv("Churn_Modelling.csv")

In [8]:
cr

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
cr.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
cr.duplicated().sum()

0

In [11]:
cr.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [12]:
X=cr.drop('Exited',axis=1)

In [13]:
X.drop(columns=["CustomerId","Surname","RowNumber"],inplace=True)

In [14]:
y=cr['Exited']

In [15]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [17]:
scalar=StandardScaler()

In [18]:
le=LabelEncoder()

In [19]:
model=LogisticRegression()

In [20]:
cat_col=X.select_dtypes('O').columns

In [21]:
cat_col

Index(['Geography', 'Gender'], dtype='object')

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
one=OneHotEncoder()

In [24]:
data=one.fit_transform(X[["Geography"]]).toarray()

In [25]:
data

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [26]:
X=X.drop('Geography',axis=1)

In [27]:
geo=pd.DataFrame(data,columns=one.get_feature_names_out())

In [28]:
geo

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [29]:
one.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [30]:
X=pd.concat([X,geo],axis=1)
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,Female,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,Male,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,Male,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,Female,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,Male,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,Female,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [31]:
X['Gender']=le.fit_transform(X["Gender"])

In [32]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [33]:
Xscaled=scalar.fit_transform(X)

In [34]:
Xtrain,Xtest,ytrain,ytest=train_test_split(Xscaled,y,test_size=.2,random_state=6)

In [35]:
model=LogisticRegression()

In [36]:
model.fit(Xtrain,ytrain)

LogisticRegression()

In [37]:
model.coef_

array([[-0.07464375, -0.24153405,  0.76311024, -0.0282634 ,  0.14276252,
        -0.06473859,  0.00372028, -0.53150253,  0.02455972, -0.12706926,
         0.23592436, -0.08975737]])

In [38]:
model.intercept_

array([-1.66013162])

In [39]:
predict=model.predict(Xtest)

In [40]:
predict

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
residual=ytest-predict

In [42]:
residual

739     0
9426    0
8200    1
5880    0
9114    0
       ..
1331    0
3820    0
2866    0
3108    0
4476    0
Name: Exited, Length: 2000, dtype: int64

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(ytest,predict)

0.812

In [45]:
import joblib

In [46]:
joblib.dump(model,"LogisticRegression.pkl")

['LogisticRegression.pkl']

In [47]:
joblib.dump(le,"Encoder.pkl")

['Encoder.pkl']

In [51]:
joblib.dump(one,'onehot.pkl')

['onehot.pkl']

In [49]:
joblib.dump(scalar,'scaler.pkl')

['scaler.pkl']